# Generated by Django 4.0.4 on 2022-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[("author", "Author"), ("subscriber", "Subscriber")],
                max_length=15,
            ),
        ),
    ]
