# Generated by Django 4.0.4 on 2022-04-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="user_id",
            new_name="user",
        ),
    ]
